changelog:
  categories:
    - title: New Features ✅
      labels:
        - 'type:feature'
    - title: Code Quality 👨‍💻
      labels:
        - 'type:code-quality'
    - title: Bug Fixes 🔧
      labels:
        - 'bug'
    - title: Misc. Fixes 🚧
      labels:
        - '*'