[package]
name = "otr-data-processor-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "otr_processor"
path = "src/lib.rs"

[[bin]]
name = "otr-processor-cli"
path = "src/main.rs"

[dependencies]
dotenv = "0.15.0"
indicatif = "0.17.7"
reqwest = { version = "0.11.24", features = ["json"] }
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
chrono = {  version = "0.4.33", features = ["serde"] }
openskill = "0.0.1"
statrs = "0.16.0"
serde_repr = "0.1.18"
lazy_static = "1.4.0"
itertools = "0.12.1"
indexmap = "2.2.6"
approx = "0.5.1"
log = "0.4.22"
strum = "0.26.3"
strum_macros = "0.26.4"
rand = "0.8.5"
criterion = "0.5.1"
tokio-postgres = "0.7.11"

[dev-dependencies]
async-once-cell = "0.5.3"
criterion = {  version = "0.5.1", features = ["html_reports"] }
httpmock = "0.7.0"
rand = { version = "0.8.5", features = ["small_rng"] }
serde_json = "1.0.114"

[lints.rust]
dead_code = "allow"
unused_variables = "allow"

[profile.release]
debug = true

[[bench]]
name = "match_processing"
harness = false
