name: Continuous Integration

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run clippy
        run: cargo clippy --all-features --all-targets

  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          toolchain: nightly

      - name: Check code formatting
        run: cargo +nightly fmt -- --check

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          touch .env
          echo "API_ROOT=${{ secrets.ENV_DEV__API_ROOT }}" >> .env
          echo "CLIENT_ID=${{ secrets.ENV_DEV__OAUTH_CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.ENV_DEV__OAUTH_CLIENT_SECRET }}" >> .env

      - name: Test
        run: cargo test
