name: Processor deploy

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: "Environment to deploy to"

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.set-tag.outputs.PRIMARY_TAG }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker Tags
        id: set-tag
        run: |
          image_prefix="${{ secrets.DOCKERHUB_USERNAME }}/otr-processor"
          if [[ "${{ inputs.target }}" == "Staging" ]]; then
            echo "PRIMARY_TAG=staging" >> $GITHUB_OUTPUT
            echo "TAGS=${image_prefix}:staging" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.target }}" == "Production" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "PRIMARY_TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            {
              echo 'TAGS<<EOF'
              echo "${image_prefix}:${{ github.ref_name }}"
              echo "${image_prefix}:latest"
              echo 'EOF'
            } >> "$GITHUB_OUTPUT"
          else
            echo "Invalid target: ${{ inputs.target }}"
            exit 1
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.set-tag.outputs.TAGS }}
