name: Deploy to Staging and Production

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Staging, Production]  # Matrix strategy for environments
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ENVIRONMENT: ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Docker image
        run: docker build -t stagecodes/otr-processor:${{ matrix.environment }} .

      - name: Push Docker image to Docker Hub
        run: docker push stagecodes/otr-processor:${{ matrix.environment }}

      # No deployment job beyond upload, the server will run the latest image when necessary.